services:
  app:
    image: ghcr.io/ximeraproject/xake2024:full_b   
    volumes:
      - ..:/code:cached
    command: /bin/sh -c "while sleep 1000; do :; done"   # run forever
    network_mode: service:ximeraserver
  ximeraserver:
    image: registry.gitlab.kuleuven.be/wet/ximera/ximeradocker:wom_b
    ports:
      - "2080:2000"          # Expose Ximera on port 2080

